---
version: '3'

services:

  traefik:
    image: traefik:latest
    command: --web --docker --docker.watch --docker.domain=${DOMAINNAME} \
             --docker.exposedbydefault=false --acme.domains=${DOMAINNAME}
    container_name: traefik
    hostname: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG}/traefik:/etc/traefik
      - ${CONFIG}/shared:/shared
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAINNAME}"
      traefik.port: "8080"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --label-enable --schedule="0 2 * * *"
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    hostname: nzbget
    ports:
      - "6788:6788"
    volumes:
      - ${CONFIG}/nzbget:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DOWNLOAD}/watch:/watch
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "6788"
      traefik.frontend.rule: "Host:nzbget.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8988:8988"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA_DIR}/TV Shows
      - ${DATA_DIR_2}/TV Shows
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8988"
      traefik.frontend.rule: "Host:sonarr.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    ports:
      - "7879:7879"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA_DIR}/Movies
      - ${DATA_DIR_2}/Movies
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "7879"
      traefik.frontend.rule: "Host:radarr.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    ports:
      - "8686:8686"
    volumes:
      - ${CONFIG}/lidarr:/config
      # - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA_DIR}/Music
      - ${DATA_DIR_2}/Music
    labels:
      traefik.enable: "true"
      traefik.port: "8686"
      traefik.frontend.rule: "Host:lidarr.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    hostname: lazylibrarian
    ports:
      - "5299:5299"
    volumes:
      - ${CONFIG}/lazylibrarian:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA_DIR}/Books
      - ${DATA_DIR_2}/Books
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "5299"
      traefik.frontend.rule: "Host:lazylibrarian.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  mylar:
    image: linuxserver/mylar:latest
    container_name: mylar
    hostname: mylar
    ports:
      - "8090:8090"
    volumes:
      - ${CONFIG}/mylar:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA_DIR}/Comics
      - ${DATA_DIR_2}/Comics
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8090"
      traefik.frontend.rule: "Host:mylar.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra2:latest
    container_name: nzbhydra
    hostname: nzbhydra
    ports:
      - "5076:5076"
    volumes:
      - ${CONFIG}/nzbhydra2:/config
      - ${DOWNLOAD}/complete:/downloads
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "5076"
      traefik.frontend.rule: "Host:nzbhydra.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  # plex:
  #   image: linuxserver/plex
  #   container_name: plex
  #   hostname: plex
  #   ports:
  #     - "32400:32400"
  #     - "32400:32400/udp"
  #     - "32469:32469"
  #     - "32469:32469/udp"
  #     - "1900:1900/udp"
  #   volumes:
  #     - ${CONFIG}/plex:/config
  #     - ${DATA}/tv:/media/tv
  #     - ${DATA}/movies:/media/movies
  #     - ${DATA}/music:/media/music
  #     - ${DATA}/anime:/media/anime
  #   environment:
  #     - PGID
  #     - PUID
  #     - TZ
  #     - VERSION=latest
  #   labels:
  #     traefik.enable: "true"
  #     traefik.port: "32400"
  #     traefik.frontend.rule: "Host:plex.${DOMAINNAME}"
  #     com.centurylinklabs.watchtower.enable: "true"
  #   restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/tautulli:/config
      - ~/Library/Logs/Plex Media Server/:/logs:ro
      # - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro # get plex running on docker, then use this
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "8181"
      traefik.frontend.rule: "Host:tautulli.${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  heimdall:
    image: duhio/heimdall-https:latest
    container_name: heimdall
    hostname: heimdall
    volumes:
      - ${CONFIG}/heimdall:/config
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:${DOMAINNAME}"
      traefik.frontend.auth.basic.usersFile: shared/.htpasswd
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    hostname: ombi
    ports:
      - "3579:3579"
    volumes:
      - ${CONFIG}/ombi:/config
    environment:
      - TZ
    labels:
      traefik.enable: "true"
      traefik.port: "3579"
      traefik.frontend.rule: "Host:ombi.${DOMAINNAME}"
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
