#!/bin/bash

SHARED_DIR="shared"

function createHtpasswd () {
  HTPASS_FILE="$SHARED_DIR/.htpasswd"
  if [ -e $HTPASS_FILE ]; then
    echo "$HTPASS_FILE already exists"
  else
    echo "Missing $HTPASS_FILE file, creating one..."
    echo "Enter the username:"
    read USERNAME
    $(htpasswd -c $HTPASS_FILE $USERNAME) # htpasswd will handle password prompts and file creation
  fi
}

function createEnv() {
  ENV_FILE=.env
  ENV_EXAMPLE=.env.example
  if [ ! -e $ENV_FILE ]; then
    $(cp $ENV_EXAMPLE $ENV_FILE)
  fi
}

function setupTraefic() {
  TRAEFIC_DIR="traefik"
  ACME_DIR="$TRAEFIC_DIR/acme"
  ACME_FILE="$ACME_DIR/acme.json"
  TOML_FILE="$TRAEFIC_DIR/traefik.toml"
  EXAMPLE_TOML=traefik.toml.example
  $(mkdir -vp $ACME_DIR)
  $(touch $ACME_FILE && chmod 600 $ACME_FILE)

  if [ ! -e $TOML_FILE ]; then
    $(cp $EXAMPLE_TOML $TOML_FILE)
  fi
}

function createDockerNetworks() {
  # TODO: test for existence so error message shuts up
  $(docker network create traefik_proxy)
}

# Create necessary files
function setup() {
  createHtpasswd
  createEnv
  setupTraefic
  createDockerNetworks
}

setup